#cloud-config
package_update: true
package_upgrade: false


ssh_pwauth: true
disable_root: false

runcmd:
  - touch /root/.hushlogin
  - unlink /etc/resolv.conf
  - echo "search rdulinux.com\nnameserver 192.168.2.15" > /etc/resolv.conf
  - apt-get update && apt install curl apt-transport-https ca-certificates lsb-release tzdata perl autofs -y

  - echo "/- /etc/auto.mount" >> /etc/auto.master
  - echo "/nfsshare -fstype=nfs,rw cloud.rdulinux.com:/nfsshare" >/etc/auto.mount
  - systemctl restart autofs
  
  - curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
  - apt update
  - FLOATING_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
  - EXTERNAL_URL="http://$FLOATING_IP" apt install gitlab-ce
  - cat /etc/gitlab/initial_root_password
