#cloud-config
package_update: true
package_upgrade: false


ssh_pwauth: true
disable_root: false

packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - lsb-release
  - tzdata
  - perl

runcmd:
  - unlink /etc/resolv.conf
  - echo "search rdulinux.com\nnameserver 192.168.2.15" > /etc/resolv.conf

