#cloud-config
package_update: true
package_upgrade: false


ssh_pwauth: true
disable_root: false

packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - lsb-release
  - tzdata
  - perl

runcmd:
  - touch /root/.hushlogin
  - unlink /etc/resolv.conf
  - echo "search rdulinux.com\nnameserver 192.168.2.15" > /etc/resolv.conf
  - curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
  - apt update
  - FLOATING_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
  - EXTERNAL_URL="http://$FLOATING_IP" apt install gitlab-ce
  - cat /etc/gitlab/initial_root_password
